# Generated by Django 5.0 on 2025-01-16 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('cust_account', models.CharField(blank=True, max_length=50)),
                ('tax_id', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PricingTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('product_desc', models.CharField(max_length=80)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('units_quantity', models.IntegerField(default=0)),
                ('unit_of_measure', models.CharField(max_length=15, null=True)),
                ('uom_code', models.CharField(blank=True, max_length=2, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('type', models.CharField(blank=True, default='0', max_length=5, null=True)),
                ('reference_product_id', models.IntegerField(default=0)),
                ('reference_product_info', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvancedPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_updated', models.DateField(blank=True, null=True)),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_type', to='api.pricingtypes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='api.products')),
            ],
        ),
    ]
