# Generated by Django 5.0 on 2025-01-16 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleStatus',
            fields=[
                ('status_code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delviery_date', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PriceListDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10)),
                ('product_description', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packaging', models.CharField(max_length=80)),
                ('units_per_package', models.IntegerField(default=0)),
                ('price_list_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_detail', to='sales.pricelistheader')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=2)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_status', models.CharField(max_length=15)),
                ('total_amount', models.FloatField(default=0)),
                ('paid_amount', models.FloatField(blank=True, default=0, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=10)),
                ('driver', models.CharField(blank=True, max_length=50)),
                ('comments', models.CharField(blank=True, max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
                ('sales_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='sales.sales_header')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shipped', models.IntegerField(default=0)),
                ('delviery_date', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('sales_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='sales.sales_detail')),
                ('shipment_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_detail', to='sales.shipmentheader')),
            ],
        ),
    ]
