# Generated by Django 5.0 on 2025-08-27 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(blank=True, max_length=10, null=True)),
                ('invoice_date', models.DateField()),
                ('total_gross_amount', models.FloatField(default=0)),
                ('total_tax_amount', models.FloatField(default=0)),
                ('total_net_amount', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customers')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_unit_price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('quantity_in_package', models.IntegerField()),
                ('gross_amount', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('net_amount', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
                ('invoice_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoiceheader')),
            ],
        ),
    ]
