# Generated by Django 5.0 on 2025-08-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='invoice_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
