# Generated by Django 5.0 on 2025-08-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoiceheader_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='line_number',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='invoicedetail',
            unique_together={('invoice_header', 'line_number')},
        ),
    ]
