# Generated by Django 5.0 on 2025-09-02 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('invoices', '0003_invoicedetail_line_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProductRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_uses', models.IntegerField(default=0)),
                ('quantity_per_invoice', models.IntegerField(default=1)),
                ('has_usage_limit', models.BooleanField(default=False)),
                ('invoice_usage_limit', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
            ],
        ),
    ]
