# Generated by Django 5.0 on 2025-09-18 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('invoices', '0004_invoiceproductrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproductrules',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_rules', to='api.products'),
        ),
    ]
